#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

################################################################################

if [[ "${@#--return-check}" = "$@" ]]
then
    echo
    echo "This script must not be run directly."
    echo
    echo "You should instead run the | setup | script and it will take care of the installation itself."
    echo
    echo "Exiting..."
    echo
    exit 1
fi

################################################################################

### Add padding to output

echo

### Determine script execution directory, install directory, and source local functions file

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
		echo
        exit 1
	fi
fi

. "$exec_dir_root/functions"

### Source openspace functions file

source_os_dna

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

### Check for any already existing installation

os-check_install_version

### All ready for installation

echo "${b}Initiating install...${x}"
echo

################################################################################

perform_installation

################################################################################

### Mark installer as completed successfully

touch "$source_dir/install_complete"
