#!/bin/bash

################################################################################

### Set bash environment error management

set -e
set -u

################################################################################

if [[ "${@#--return-check}" = "$@" ]]
then
    echo
    echo "This script must not be run directly."
    echo
    echo "You should instead run the | setup | script and it will take care of the installation itself."
    echo
    echo "Exiting..."
    echo
    exit 1
fi

################################################################################

### Source local functions file

echo
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$source_dir" == */tools ]]
then
        source_dir="${source_dir%/tools}"
fi

. "$source_dir/functions"

### Source openspace functions file

source_os_functions

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

### Check for any already existing installation

os-check_install_version

### All ready for installation

echo "${b}Initiating install...${x}"
echo

################################################################################

perform_installation

################################################################################

### Mark installer as completed successfully

touch "$source_dir/install_complete"
