#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

### Add padding to output

echo

### Determine script execution directory, install directory, and source local functions file

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
		echo
        exit 1
	fi
fi

. "$exec_dir_root/functions"

### Check for root user runtime

check_root

### Evaluate command arguments for custom-version install

while getopts ":d:p:" arguments
do
    case $arguments in
        d)	export custom_dna_version="$OPTARG"
	        ;;
		p)	export custom_project_version="$OPTARG"
	        ;;
        \?)	echo "Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |."
	        echo
	        exit
	        ;;
    esac
done
OPTIND=1

### Download openspace dna

if [ ! -z "${custom_dna_version-}" ]
then
	case $custom_dna_version in
		b)	echo "Fetching bleeding-edge dna version as per | -d b |."
			echo
			download_os_dna
			;;
		l)	echo "Disabling dna fetch and using local version as per | -d l |."
			echo
			;;
		*)	echo "Invalid content for | custom_dna_version | in function | ${FUNCNAME[0]} |."
			echo
			echo "Exiting..."
			echo
			exit
			;;
	esac
fi

### Source openspace dna

source_os_dna

### Define formatting

dna-define_formatting

### Define variables

define_vars

################################################################################

### Actually run the installer

dna-run_install
