#!/usr/bin/env bash

set -e
set -u

echo "Now creating all-in-one TLS file from LetsEncrypt wildcard cert for ejabberd..."
echo

le_dir="/etc/letsencrypt/live"
tls_dir="/etc/ssl/aenigma"

for le_cert_domain_full in "$le_dir"/*
do

    le_cert_domain="$(echo ${le_cert_domain_full} | sed 's:.*/::')"

    echo "Now creating all-in-one TLS certificate file for ${le_cert_domain}..."
    echo

    touch "${tls_dir}/${le_cert_domain}.pem"

    cat "${le_dir}/${le_cert_domain}/privkey.pem" > "${tls_dir}/${le_cert_domain}.pem"
    cat "${le_dir}/${le_cert_domain}/fullchain.pem" >> "${tls_dir}/${le_cert_domain}.pem"

    echo "Finished creating all-in-one TLS file for ${le_cert_domain}."
    echo

    echo "Now copying individual fullchain and privkey files for ${le_cert_domain}..."
    echo

    mkdir -p "${tls_dir}/${le_cert_domain}.d/"

    cp "${le_dir}/${le_cert_domain}/privkey.pem" "${tls_dir}/${le_cert_domain}.d/"
    cp "${le_dir}/${le_cert_domain}/fullchain.pem" "${tls_dir}/${le_cert_domain}.d/"

    echo "Finished copying individual fullchain and privkey files for ${le_cert_domain}."
    echo

done

chown -R "ejabberd:ejabberd" "${tls_dir}" 2> /dev/null || true
chmod -R 700 "${tls_dir}"

echo "Finished creating all-in-one TLS files."
echo
