#!/usr/bin/env bash

set -e
set -u

echo "Now creating all-in-one TLS files for all LetsEncrypt provisioned certs for ejabberd..."
echo

#chgrp -R ssl-cert /etc/letsencrypt
#chmod -R g=rX /etc/letsencrypt
#chmod 750 /etc/letsencrypt/live/
#chmod 750 /etc/letsencrypt/archive/

le_dir=/etc/letsencrypt/live
tls_dir=/etc/ssl/aenigma

for le_cert_domain_full in "$le_dir"/*
do

    le_cert_domain="$(echo $le_cert_domain_full | sed 's:.*/::')"

    echo "Now creating all-in-one TLS file for $le_cert_domain..."
    echo

    touch "$tls_dir/$le_cert_domain.pem"
    cat "$le_dir/$le_cert_domain/privkey.pem" > "$tls_dir/$le_cert_domain.pem"
    cat "$le_dir/$le_cert_domain/fullchain.pem" >> "$tls_dir/$le_cert_domain.pem"

    echo "Finished creating all-in-one TLS file for $le_cert_domain."
    echo

done

chown -R ejabberd:ejabberd $tls_dir || true
chmod -R 700 $tls_dir

echo "Finished creating all-in-one TLS files."
echo
