#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

################################################################################

### Add padding to output

echo

### Determine script execution directory, install directory, and source local functions file

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
		echo
        exit 1
	fi
fi

. "$exec_dir_root/functions"

### Source openspace functions file

source_os_dna

### Define formatting

dna-define_formatting

### Define variables

define_vars

### Check for root execution

check_root

################################################################################

dna-head_script

dna-read_conf_settings

################################################################################

if [ ! "${cluster_mode-null}" = "primary" ]
then
	dna-echo -e "This script must only be run on the primary node of your ${short_name} instance."
	dna-exit
fi

################################################################################

### Fetch IP addresses for this machine

dna-get_public_ipv4
dna-check_ipv6_connectivity

### Insert IP changed warning here ###

### Update routing info on this machine

aenigma-update_routing_info

### Push and update routing info on all secondary nodes to allow them to connect to each other correctly.

aenigma-push_routing_info
