#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

################################################################################

### Start fresh

clear

################################################################################

### Determine script execution directory and install directory.

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | ${exec_dir} |."
		echo
		echo "Exiting..."
		echo
        exit 1
	fi
fi

### Source local functions file.

. "$exec_dir_root/functions"

################################################################################

### Define formatting

synthia-define_formatting

################################################################################

### Check for root user runtime

synthia-check_root

################################################################################

### Source dna

synthia-source_dna

################################################################################

### Define variables

synthia-define_vars

################################################################################

### Head shell

if [[ $- == *i* ]]
then
        dna-echo -m "${g-}You are now inside of the aenigma-env shell."
        export PS1="\u@aenigma-env:\[\e[32m\]~#\[\e[m\] "
else
        dna-echo -e "This file is NOT intended to be run directly."
        dna-echo -m "It is only intended to be sourced by the command:"
        dna-echo -m " | ${y-}bash --init-file ${exec_dir}/${proj_name}-env${n-} |"
        dna-echo -m "to enter the developement environment of this project."
        dna-exit
fi

################################################################################
