#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

################################################################################

### Start fresh

clear

################################################################################

### Determine script execution directory and install directory.

if [ -L "${BASH_SOURCE}" ]
then

    ### This file is being executed via a symlink.
    ### Identify the parent directory of the target file

    link_target="$(readlink ${BASH_SOURCE})"
    exec_dir="${link_target%/*}"

else

    ### This file is being directly executed.
    ### Identify our parent directory.

    exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

fi

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | ${exec_dir} |."
		echo
		echo "Exiting..."
		echo
        exit 1
	fi
fi

### Source local functions file.

. "$exec_dir_root/functions"

################################################################################

### Define formatting

synthia-define_formatting

################################################################################

### Check for root user runtime

synthia-check_root

################################################################################

### Head upgrade

echo "${g-}${b-}Initiating upgrade...${x-}"
echo

################################################################################

### Evaluate command arguments for custom-version install

while getopts ":d:p:o:" arguments
do
    case $arguments in
        d)	export custom_dna_version="${OPTARG}"
	        ;;
		p)	export custom_project_version="${OPTARG}"
	        ;;
        o)	export custom_output="${OPTARG}"
        ;;
        \?)	echo "${r-}${b-}Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |.${x-}"
	        echo
			echo "${b-}Exiting...${x-}"
			echo
	        exit 1
	        ;;
    esac
done
OPTIND=1

### Download dna

synthia-download_dna

### Source dna

synthia-source_dna

################################################################################

### Define variables

synthia-define_vars

################################################################################

if [[ "${custom_project_version-null}" == "l" ]]                                  ### Do NOT escape the string comparison
then

	echo
    dna-echo -e "You're running the installation via the upgrade script."
    dna-echo -m "Therefore the | ${r-}local${n-} | version of the ${proj_name} directory doesn't exist, as it's cloned automatically by the upgrade script itself."
    dna-echo -m "If you want to make customizations to the project before installing it, clone it yourself while in the root directory of the root user and then run:"
    dna-echo -m " | ${c-}bash ${proj_name}/setup -pl | "
    dna-exit

fi

################################################################################

### Clone and upgrade

if [ -d "/root/${proj_name}/" ]
then
        rm -r "/root/${proj_name}/"
fi

echo

cd

git clone "${git_host}/${author_name}/${proj_name}"

dna-run_install

################################################################################
